AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Udagram Application Stack
  Deploys EC2 instances in an Auto Scaling Group behind an Application Load Balancer (NGINX preinstalled).

Parameters:
  EnvironmentName:
    Type: String
    Default: udagram
    Description: A name prefix applied to all app resources.

  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues:
      - t2.micro
      - t3.micro
      - t3.small
    Description: EC2 instance type for the web servers.

Resources:
  ####################################################
  # IAM ROLE AND INSTANCE PROFILE
  ####################################################
  AppRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  AppInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref AppRole

  ####################################################
  # SECURITY GROUPS
  ####################################################
  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP from the internet
      VpcId: !ImportValue udagram-VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP from ALB to EC2
      VpcId: !ImportValue udagram-VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref AlbSecurityGroup

  ####################################################
  # LAUNCH TEMPLATE
  ####################################################
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        IamInstanceProfile:
          Name: !Ref AppInstanceProfile
        ImageId: ami-083b3f53cbda7e5a4  # ✅ Latest Amazon Linux 2 AMI (us-east-2)
        InstanceType: !Ref InstanceType
        NetworkInterfaces:
          - AssociatePublicIpAddress: false
            DeviceIndex: 0
            Groups:
              - !Ref AppSecurityGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            amazon-linux-extras install nginx1 -y
            systemctl enable nginx
            systemctl start nginx
            echo "<h1>Udagram is Live!</h1><p>Deployed via CloudFormation 🚀</p>" > /usr/share/nginx/html/index.html

  ####################################################
  # LOAD BALANCER AND TARGET GROUP
  ####################################################
  AppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !ImportValue udagram-VPCID
      Protocol: HTTP
      Port: 80
      TargetType: instance
      HealthCheckPath: /
      Matcher:
        HttpCode: 200

  AppLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets: !Split [",", !ImportValue udagram-PublicSubnets]
      SecurityGroups:
        - !Ref AlbSecurityGroup
      Scheme: internet-facing
      Type: application

  AppListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref AppLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref AppTargetGroup

  ####################################################
  # AUTO SCALING GROUP
  ####################################################
  AppAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier: !Split [",", !ImportValue udagram-PrivateSubnets]
      MinSize: 2
      MaxSize: 4
      DesiredCapacity: 2
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      TargetGroupARNs:
        - !Ref AppTargetGroup
      HealthCheckType: ELB
      HealthCheckGracePeriod: 120

Outputs:
  LoadBalancerURL:
    Description: Application Load Balancer URL
    Value: !Sub "http://${AppLoadBalancer.DNSName}"
